sonar.projectKey=link-it_govpay-portal
sonar.organization=link-it

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/govpay-portal/clover.xml
sonar.javascript.lcov.reportPaths=coverage/govpay-portal/clover.xml

sonar.sourceEncoding=UTF-8
